language: c

sudo: false

env:
  global:
    - LUAROCKS_VERSION="2.4.1"
    - ROCK_NAME="families"
    - ROCK_VERSION="0.1-1"
  matrix:
    - LUA_VERSION="5.2.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-alfa"
    - LUA_VERSION="5.3.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-beta"
    - LUA_VERSION="5.3.4" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-gama"

before_install:
  - bash travis-ci.sh

install:
  - export "PATH=$TRAVIS_CACHE_DIRECTORY/bin:$PATH"
  - luarocks install luasocket
  - luarocks install LuaFileSystem
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install luacheck

cache:
  directories:
    - "$HOME/.travis-ci-lua-alfa"
    - "$HOME/.travis-ci-lua-beta"
    - "$HOME/.travis-ci-lua-gama"

script:
  - export "PATH=$TRAVIS_CACHE_DIRECTORY/bin:$PATH"
  - luarocks lint "$ROCK_NAME-$ROCK_VERSION.rockspec"
  - luacheck --std max+busted src spec
  - busted --verbose --coverage spec
  - luarocks make
  - lua -lfamilies -e "print ('Library $ROCK_NAME was loaded successfully...')"

after_success:
  - export "PATH=$TRAVIS_CACHE_DIRECTORY/bin:$PATH"
  - luacov-coveralls -i src --dryrun
  - luacov-coveralls -i src

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
