language: c

sudo: false

env:
  global:
    - LUAROCKS_VERSION="2.4.1"
    - ROCK_NAME="families"
    - ROCK_VERSION="0.1-1"
  matrix:
    - LUA_VERSION="5.1.4" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-1-4" REBUILD_LUA=1
    - LUA_VERSION="5.2.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-2-1" REBUILD_LUA=1
    - LUA_VERSION="5.2.4" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-2-4" REBUILD_LUA=1
    - LUA_VERSION="5.3.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-3-1" REBUILD_LUA=1
    - LUA_VERSION="5.3.4" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-3-4" REBUILD_LUA=1
    - LUA_VERSION="5.3.6" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-3-6" REBUILD_LUA=1
    - LUA_VERSION="5.4.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-5-4-1" REBUILD_LUA=1

before_install:
  - source travis-ci.sh

install:
  - luarocks install luasocket
  - luarocks install LuaFileSystem
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install luacheck

cache:
  directories:
    - "$HOME/.travis-ci-lua-5-1-4"
    - "$HOME/.travis-ci-lua-5-2-1"
    - "$HOME/.travis-ci-lua-5-2-4"
    - "$HOME/.travis-ci-lua-5-3-1"
    - "$HOME/.travis-ci-lua-5-3-4"
    - "$HOME/.travis-ci-lua-5-3-6"
    - "$HOME/.travis-ci-lua-5-4-1"

script:
  - luarocks lint "$ROCK_NAME-$ROCK_VERSION.rockspec"
  - luacheck --std max+busted src spec
  - busted --verbose --coverage spec
  - luarocks make
  - eval `luarocks path`
  - lua -lfamilies -e "print ('Library $ROCK_NAME was loaded successfully...')"

after_success:
  - luacov-coveralls -i src --dryrun
  - luacov-coveralls -i src

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
