language: c

sudo: false

env:
  global:
    - LUAROCKS_VERSION="2.4.1"
  matrix:
    - LUA_VERSION="5.2.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-alfa"
    - LUA_VERSION="5.3.1" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-beta"
    - LUA_VERSION="5.3.4" TRAVIS_CACHE_DIRECTORY="$HOME/.travis-ci-lua-gama"

before_install:
  - bash travis-ci.sh

install:
  - "$TRAVIS_CACHE_DIRECTORY/bin/luarocks install luasocket"
  - "$TRAVIS_CACHE_DIRECTORY/bin/luarocks install LuaFileSystem"
  - "$TRAVIS_CACHE_DIRECTORY/bin/luarocks install busted"

cache:
  directories:
    - "$HOME/.travis-ci-lua-alfa"
    - "$HOME/.travis-ci-lua-beta"
    - "$HOME/.travis-ci-lua-gama"

script:
  - busted spec

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
